version: '3'
services:
    {{ cookiecutter.service }}:
      env_file:
        - ../${VAULT_ENV_FILE}
      build:
        context: ..
        dockerfile: deployments/Dockerfile
      depends_on: []
      network_mode: host
